# Generated by Django 2.0 on 2019-11-20 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Modules',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='模块名称')),
                ('describe', models.TextField(blank=True, default='', null=True, verbose_name='模块简介')),
                ('tester', models.CharField(max_length=200, verbose_name='测试人员')),
                ('developer', models.CharField(blank=True, max_length=100, verbose_name='开发人员')),
                ('status', models.BooleanField(default=1, verbose_name='模块状态')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '模块管理',
                'verbose_name_plural': '模块管理',
            },
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='项目名称')),
                ('describe', models.TextField(blank=True, default='', null=True, verbose_name='项目简介')),
                ('status', models.BooleanField(default=1, verbose_name='项目状态')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '项目管理',
                'verbose_name_plural': '项目管理',
            },
        ),
        migrations.AddField(
            model_name='modules',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Projects', verbose_name='所属项目'),
        ),
    ]
