# Generated by Django 2.0 on 2019-11-20 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterfaceCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='用例名称')),
                ('api', models.CharField(max_length=100, verbose_name='接口路径')),
                ('method', models.CharField(choices=[('0', 'GET'), ('1', 'POST'), ('2', 'DELETE'), ('3', 'PUT')], default='0', max_length=10, verbose_name='请求方法')),
                ('header', models.TextField(verbose_name='请求头')),
                ('param_type', models.CharField(choices=[('0', 'form-data'), ('1', 'json'), ('2', 'params')], default='0', max_length=10, verbose_name='参数类型')),
                ('param_body', models.TextField(verbose_name='参数内容')),
                ('assert_type', models.CharField(choices=[('0', '包含'), ('1', '匹配')], default='0', max_length=10, verbose_name='断言类型')),
                ('assert_body', models.TextField(verbose_name='断言内容')),
                ('describe', models.TextField(blank=True, default='', null=True, verbose_name='用例描述')),
                ('status', models.BooleanField(default=1, verbose_name='状态')),
                ('maker', models.CharField(blank=True, max_length=200, null=True, verbose_name='创建者')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Modules', verbose_name='所属模块')),
            ],
            options={
                'verbose_name': '接口用例',
                'verbose_name_plural': '接口用例',
            },
        ),
    ]
