# Generated by Django 2.0 on 2019-12-05 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apitest', '0003_auto_20191201_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testtask',
            name='status',
            field=models.CharField(choices=[('0', '未执行'), ('1', '执行中'), ('2', '执行完成')], default='0', max_length=50, verbose_name='状态'),
        ),
    ]
